// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdsEjWDtmiaC_kqt-jVkJBZpFSzRQ23j0',
    appId: '1:32666477733:web:f6178d3720e8d4d115194c',
    messagingSenderId: '32666477733',
    projectId: 'cryptobot-c263e',
    authDomain: 'cryptobot-c263e.firebaseapp.com',
    storageBucket: 'cryptobot-c263e.appspot.com',
    measurementId: 'G-6DZ93JJSTG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTAUV0Z_BCVJcz7mUyvPIQBGSlcJt5-rQ',
    appId: '1:32666477733:android:a4385f60cf062ed015194c',
    messagingSenderId: '32666477733',
    projectId: 'cryptobot-c263e',
    storageBucket: 'cryptobot-c263e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3-bYbmtYe922Mxbfkvrub7hryHloD-wc',
    appId: '1:32666477733:ios:a353327b1e0253f115194c',
    messagingSenderId: '32666477733',
    projectId: 'cryptobot-c263e',
    storageBucket: 'cryptobot-c263e.appspot.com',
    androidClientId: '32666477733-7mj5lglm7b4qsepb5jonmt62hd3pvid2.apps.googleusercontent.com',
    iosClientId: '32666477733-dcglcicq3hv5igqbh68etohcb6jne1d6.apps.googleusercontent.com',
    iosBundleId: 'com.scorefy.cryptobot',
  );
}
